permissions:
  id-token: write # This is required for requesting the JWT

on: 
  push:
    branches:
      - main
      - releases**
    paths-ignore:
      - '.github/**' # this will allow ignore changes in workflow files

  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FOLDER_ID: b1gsuimj95h9vl0j2f11
  SA_ID: ajegot41f9ofbcmqpm3l
  FUNCTION_NAME: crop-image-prod
  FUNCTION_RUNTIME: nodejs18
  FUNCTION_ENTRYPOINT: index.handler
  FUNCTION_MEMORY: 128Mb
  
jobs:
  build:
    environment: prod
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Function
        id: sls-func
        uses: yc-actions/yc-sls-function@v3.1.0
        with:
          yc-sa-id: ${{env.SA_ID}}
          folder-id: ${{env.FOLDER_ID}}
          function-name: ${{env.FUNCTION_NAME}}
          runtime: ${{env.FUNCTION_RUNTIME}}
          memory: ${{env.FUNCTION_MEMORY}}
          entrypoint: ${{env.FUNCTION_ENTRYPOINT}}
          include: |
            **/*.json
            **/*.js

